name = "post_receive"
version = "0.1.0"


[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
envoy = ">= 1.0.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleamyshell = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleescript = ">= 1.3.0 and < 2.0.0"
